# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run test
    runs-on: ${{ matrix.macos_version }}

    strategy:
      matrix:
        macos_version: [macos-15]
        xcode_version: ['16.0.0'] #https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#xcode

    steps:
    - uses: actions/checkout@v4

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: ${{ matrix.xcode_version }}

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
